api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  file:
    filename: /etc/traefik/config.yml
    watch: true

http:
  routers:
    traefik:
      rule: "Host(`traefik.swarm.localhost`)"
      service: api@internal
    whoami:
      rule: "Host(`whoami.swarm.localhost`)"
      service: whoami

  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami:80"
