services:
  traefik:
    image: traefik:v1.7
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.toml:/traefik.toml:ro
    networks:
      - web

  whoami1:
    image: traefik/whoami:latest
    container_name: whoami1
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.swarm.localhost"
      - "traefik.port=80"

  whoami2:
    image: traefik/whoami:latest
    container_name: whoami2
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.swarm.localhost"
      - "traefik.port=80"

  whoami3:
    image: traefik/whoami:latest
    container_name: whoami3
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.swarm.localhost"
      - "traefik.port=80"

networks:
  web:
    driver: bridge
